name: merhaba_app
description: "Rastgele görüntülü sohbet, arkadaşlık ve mesajlaşma uygulaması."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_webrtc: ^1.5.2
  socket_io_client: ^2.0.3+1
  permission_handler: ^11.3.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  firebase_core: ^4.11.0
  firebase_messaging: ^16.3.0
  flutter_local_notifications: ^21.0.0
  package_info_plus: ^8.1.2
  url_launcher: ^6.3.1
  firebase_crashlytics: ^5.2.6
  image_picker: ^1.1.2
  geolocator: ^14.0.2
  record: ^7.1.1
  audioplayers: ^6.8.1
  path_provider: ^2.1.6
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
